#!/bin/bash
set -ex

if [ z$NB_UID == 'z' ]; then
  conda env update --file environment-post.yml
else
  conda env update --file environment-post.yml -n root
fi

jupyter labextension install \
    @jupyter-widgets/jupyterlab-manager \
    @jupyterlab/geojson-extension \
    bqplot \
    jupyter-leaflet \
  && jupyter labextension list
